var sitemap = 
{
"rootNodes":[
{
"pageName":"登录及选择",
"type":"Wireframe",
"url":"登录及选择.html",
"children":[
{
"pageName":"登录",
"type":"Wireframe",
"url":"登录.html"},
{
"pageName":"应用选择",
"type":"Wireframe",
"url":"应用选择.html"}]},
{
"pageName":"收货作业",
"type":"Wireframe",
"url":"收货作业.html",
"children":[
{
"pageName":"调拨收货",
"type":"Wireframe",
"url":"调拨收货.html",
"children":[
{
"pageName":"SKU收货",
"type":"Wireframe",
"url":"SKU收货.html"}]},
{
"pageName":"短收原因维护",
"type":"Wireframe",
"url":"短收原因维护.html"},
{
"pageName":"PO收货",
"type":"Wireframe",
"url":"PO收货.html",
"children":[
{
"pageName":"PO收货明细",
"type":"Wireframe",
"url":"PO收货明细.html"}]}]},
{
"pageName":"出货作业",
"type":"Wireframe",
"url":"出货作业.html",
"children":[
{
"pageName":"退厂商-新建\/修改",
"type":"Wireframe",
"url":"退厂商-新建_修改.html"},
{
"pageName":"退大仓-新建\/修改",
"type":"Wireframe",
"url":"退大仓-新建_修改.html"},
{
"pageName":"退调拨-门店-新建\/修改",
"type":"Wireframe",
"url":"退调拨-门店-新建_修改.html"},
{
"pageName":"退调拨-采购-新建",
"type":"Wireframe",
"url":"退调拨-采购-新建.html"},
{
"pageName":"退调拨-采购-修改",
"type":"Wireframe",
"url":"退调拨-采购-修改.html",
"children":[
{
"pageName":"退调拨-采购-调整",
"type":"Wireframe",
"url":"退调拨-采购-调整.html"}]}]},
{
"pageName":"查询&报表",
"type":"Wireframe",
"url":"查询_报表.html",
"children":[
{
"pageName":"出货查询",
"type":"Wireframe",
"url":"出货查询.html",
"children":[
{
"pageName":"出货明细",
"type":"Wireframe",
"url":"出货明细.html"}]},
{
"pageName":"收货查询",
"type":"Wireframe",
"url":"收货查询.html"}]}]};
