package com.task.bean;

import java.util.ArrayList;
import java.util.Hashtable;
import java.util.List;

import com.task.db.DBOperator;

public class INTXBean {
	
	private DBOperator dbo = new DBOperator();
	
	public List getData(){
		List list = new ArrayList();
		try{
			String sql = "select * from mm4n4lib.ITXSKUW where INSTNO='20110900010' and integer(INUMBR)>=100000000 and integer(INUMBR)<10000000000";
			Hashtable ht = new Hashtable();
			ht.put("Url", "jdbc:as400://172.16.251.37;naming=sql;errors=full");
			ht.put("Driver", "com.ibm.as400.access.AS400JDBCDriver");
			ht.put("UserName", "JAVAMIS");
			ht.put("Pwd", "JAVAMIS");
			
			list = dbo.getData(sql, new Object[0], ht);
		}catch(Exception e){
			e.printStackTrace();
		}
		System.out.println("get data end");
		return list;
	}

	public void putData(){
		try{
			String sql = "insert into IDS.TMP_PRODUCT (INSTNO,PRODUCTID,DBTIME,TRAN_TYPE,UPC,NAME,WIDTH,HEIGHT,DEPTH1,COLOR,ABBREVNAME,SIZE1,UOM,MANUFACTURER,CATEGORY,SUPPLIER,INNERPACK,XNESTING,YNESTING,ZNESTING,PEGHOLES,PEGHOLEX,PEGHOLEY,PEGHOLEWIDTH,PEGHOLE2X,PEGHOLE2Y,PEGHOLE2WIDTH,PEGHOLE3X,PEGHOLE3Y,PEGHOLE3WIDTH,PACKAGESTYLE,PEGID,FINGERSPACEY,JUMBLEFACTOR,PRICE,CASECOST,TAXCODE,UNITMOVEMENT,SHARE1,CASEMULTIPLE,DAYSSUPPLY,COMBINEDPERFORMANCEINDEX,PEGSPAN,MINIMUMUNITS,MAXIMUMUNITS,SHAPEID,BITMAPIDOVERRIDE,TRAYWIDTH,TRAYHEIGHT,TRAYDEPTH,TRAYNUMBERWIDE,TRAYNUMBERHIGH,TRAYNUMBERDEEP,TRAYTOTALNUMBER,TRAYMAXHIGH,CASEWIDTH,CASEHEIGHT,CASEDEPTH,CASENUMBERWIDE,CASENUMBERHIGH,CASENUMBERDEEP,CASETOTALNUMBER,CASEMAXHIGH,DISPLAYWIDTH,DISPLAYHEIGHT,DISPLAYDEPTH,DISPLAYNUMBERWIDE,DISPLAYNUMBERHIGH,DISPLAYNUMBERDEEP,DISPLAYTOTALNUMBER,DISPLAYMAXHIGH,ALTERNATEWIDTH,ALTERNATEHEIGHT,ALTERNATEDEPTH,ALTERNATENUMBERWIDE,ALTERNATENUMBERHIGH,ALTERNATENUMBERDEEP,ALTERNATETOTALNUMBER,ALTERNATEMAXHIGH,LOOSEWIDTH,LOOSEHEIGHT,LOOSEDEPTH,LOOSENUMBERWIDE,LOOSENUMBERHIGH,LOOSENUMBERDEEP,LOOSETOTALNUMBER,LOOSEMAXHIGH,MERCHXMIN,MERCHXMAX,MERCHXUPRIGHTS,MERCHXCAPS,MERCHXPLACEMENT,MERCHXNUMBER,MERCHXSIZE,MERCHXDIRECTION,MERCHXSQUEEZE,MERCHYMIN,MERCHYMAX,MERCHYUPRIGHTS,MERCHYCAPS,MERCHYPLACEMENT,MERCHYNUMBER,MERCHYSIZE,MERCHYDIRECTION,MERCHYSQUEEZE,MERCHZMIN,MERCHZMAX,MERCHZUPRIGHTS,MERCHZCAPS,MERCHZPLACEMENT,MERCHZNUMBER,MERCHZSIZE,MERCHZDIRECTION,MERCHZSQUEEZE,NUMBEROFPOSITIONS,UNITCOST,DESC1,DESC2,DESC3,DESC4,DESC5,DESC6,DESC7,DESC8,DESC9,DESC10,DESC11,DESC12,DESC13,DESC14,DESC15,DESC16,DESC17,DESC18,DESC19,DESC20,DESC21,DESC22,DESC23,DESC24,DESC25,DESC26,DESC27,DESC28,DESC29,DESC30,DESC31,DESC32,DESC33,DESC34,DESC35,DESC36,DESC37,DESC38,DESC39,DESC40,DESC41,DESC42,DESC43,DESC44,DESC45,DESC46,DESC47,DESC48,DESC49,DESC50,VALUE1,VALUE2,VALUE3,VALUE4,VALUE5,VALUE6,VALUE7,VALUE8,VALUE9,VALUE10,VALUE11,VALUE12,VALUE13,VALUE14,VALUE15,VALUE16,VALUE17,VALUE18,VALUE19,VALUE20,VALUE21,VALUE22,VALUE23,VALUE24,VALUE25,VALUE26,VALUE27,VALUE28,VALUE29,VALUE30,VALUE31,VALUE32,VALUE33,VALUE34,VALUE35,VALUE36,VALUE37,VALUE38,VALUE39,VALUE40,VALUE41,VALUE42,VALUE43,VALUE44,VALUE45,VALUE46,VALUE47,VALUE48,VALUE49,VALUE50,FLAG1,FLAG2,FLAG3,FLAG4,FLAG5,FLAG6,FLAG7,FLAG8,FLAG9,FLAG10,MINIMUMSQUEEZEFACTORX,MINIMUMSQUEEZEFACTORY,MINIMUMSQUEEZEFACTORZ,MAXIMUMSQUEEZEFACTORX,MAXIMUMSQUEEZEFACTORY,MAXIMUMSQUEEZEFACTORZ,FILLPATTERN,XFILENAME,BRAND,SUBCATEGORY,WEIGHT,PLANOGRAMALIAS,FRONTOVERHANG,FINGERSPACEX,STATUS,DATECREATED,DATEMODIFIED,DATEPENDING,DATEEFFECTIVE,DATEFINISHED,DATE1,DATE2,DATE3,CREATEDBY,MODIFIEDBY,TRANSPARENCY,PEAKSAFETYFACTOR,BACKROOMSTOCK,DELIVERYSCHEDULE,DBDATEEFFECTIVEFROM,DBDATEEFFECTIVETO,PARTID,UNAUTHORIZED,BITMAPIDOVERRIDEUNIT,MODELFILENAMEUNIT,CAPACITYUNRESTRICTED,DEFAULTMERCHSTYLE,AUTOMATICMODEL,CUSTOMDATA,DBGUID,SOURCE,TECHNICALKEY) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
			Hashtable ht = new Hashtable();
			ht.put("Url", "jdbc:oracle:thin:@10.130.1.53:1521:IKBTEST");
			ht.put("Driver", "oracle.jdbc.OracleDriver");
			ht.put("UserName", "jda_user");
			ht.put("Pwd", "jda_user");
			
			dbo.execDataByTrancation(ht, sql, this.getData());
		}catch(Exception e){
			e.printStackTrace();
		}
	}
	
	public static void main(String[] args){
		INTXBean intx = new INTXBean();
		intx.putData();
	}
	
}
